include: package:total_lints/app.yaml

analyzer:
  errors:
    lines_longer_than_80_chars: ignore
  exclude:
    - lib/src/wip

linter:
  rules:
    prefer_if_elements_to_conditional_expressions: false
